<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>askwam-reference-msal</AssemblyName>
    <RootNamespace>AskWam.Reference.Msal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.89.0" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.89.0" />
  </ItemGroup>
</Project>
